- windows.md
Reverts upleveled/system-setup#9
This causes strange problems such as:
```
/D/upleveled-softwork/courses/slide-decks (add-web-terminology-deck)
$ yarn mdx-deck state-management/index.mdx
yarn run v1.22.5
$ D:\upleveled-softwork\courses\slide-decks\node_modules\.bin\mdx-deck state-management/index.mdx
/usr/bin/bash: D:upleveled-softworkcoursesslide-decksnode_modules.binmdx-deck: command not found
```
> Revert "Use Git Bash as Yarn Shell in Windows system setup"

- windows.md
Some students report adb not being a command in their system setup. 
After some research, it seems the new installation command ` choco install androidstudio` is not setting the right path for the `adb` binary being found.
this PR achieve:
1.  Add a command that set the path properly after choco installation
2.  Add a manual check for the adb command being found by the shell
> Add adb path instructions to windows setup

- linux.md
- macos.md
- windows.md
There was a new release for PostgreSQL (version 15). I replaced '14' by '15' in the Windows, Mac and Linux setup files in the installation commands.
> Update info for PostgreSQL version 15

- linux.md
- macos.md
- windows.md
Since we're using CSS Modules with Sass (scss) with Next.js 13+ and the app directory, we need to enable Stylelint for these syntaxes
> Enable Stylelint for scss

- windows.md
This PR corrects a minor typo in our Windows system setup guide, which previously said to use Homebrew. The guide has now been updated to Chocolatey instead.
> Update Homebrew to Chocolatey in Windows guide

- linux.md
- macos.md
- windows.md
Issue:
- https://github.com/facebook/metro/issues/1
All system setup guides contain a step to set up a project using `create-expo-app` to test if Expo and React Native are set up properly. Metro (the bundler used in React Native) has problems when performing this step with `pnpm`:
```
Error: Unable to resolve module ./node_modules/expo/AppEntry
```
This is caused by duplicate dependencies in nested `node_modules` folders, which pnpm creates to improve performance and reduce disk space usage.
To fix this issue, this PR adds a script that configures the `node-linker` option to `hoisted` in the `.npmrc` file and then runs `pnpm install --force` to recreate the dependencies. This ensures that dependencies are installed at the top level instead of being duplicated in nested folders.
Once Expo …
> Switch to pnpm hoisted linker in Expo .npmrc

- linux.md
- macos.md
- windows.md
This PR simplifies the instructions for setting up a new React Native app with Expo. We have updated the command to `pnpm create expo` as it is more likely to be supported in the future. The change is based on [a tweet from Evan Bacon](https://twitter.com/Baconbrix/status/1652372955450441729). By following this updated guide, you'll be able to create a new React Native app with Expo using a more efficient and future-proof setup method.
> Switch to `create-expo`

- linux.md
- macos.md
- windows.md
This PR updates the Expo app setup command to include the latest version, by adding the `@latest` tag. With this change, we ensure that the latest version of Expo is installed when creating a new app.
> Update `create expo` to use `@latest`

- linux.md
We encountered an issue during the installation of the `libpg-query` dependency while running the ESLint commands on a Linux Ubuntu machine. The error message indicated that `gyp ERR! stack Error: not found: make` was causing the problem. 
To resolve this issue, we have added the installation of [the `build-essential` metapackage](https://packages.ubuntu.com/kinetic/build-essential), which includes the necessary tools and dependencies like `make`, to the System Setup. This package will provide the required components for building native code and resolving the `node-gyp` error.
```
Progress: resolved 643, reused 614, downloaded 0, added 0, done
node_modules/.pnpm/libpg-query@15.0.2/node_modules/libpg-query: Running install script, failed in 1.7s
.../node_modules/libpg-query install$ …
```
> Add `build-essential` metapackage to Linux setup

- linux.md
- macos.md
- windows.md
This PR adds the option for the VS Code user `settings.json` file to enable Prettier find the `.sql` files and format them using Prettier (with the `prettier-plugin-sql` plugin)
> Add prettier.documentSelectors for SQL files

- windows.md
Closes #31
Upgrade the `choco` command to use `visualstudio2022-workload-vctools` instead of `visualstudio2017-workload-vctools` and removing the `npm` configuration line for setting `msvs_version to 2017`, as it is [no longer necessary](https://github.com/upleveled/system-setup/issues/31#issuecomment-1689874786) with the updated Visual Studio version.
> Upgrade to Visual Studio 2022

- linux.md
Closes #55 
The curl command-line tool isn't pre-installed in Linux Ubuntu. To make sure the System Setup works as intended, this PR adds a step to install curl before its usage.
> Add curl installation step to Linux setup

- linux.md
Follow-up to #59
This PR replaces `apt-get` with `apt` in all installation commands. Using `apt` is the recommended approach, keeping our setup guide current. 
Additionally, adding the install command for Flatpack, because we are using it for the installation of Kooha.
> Update to `apt`, add Flatpak installation

- linux.md
- macos.md
- windows.md
Closes #58 
Closes #42
Students have found an `ERR_PNPM_NO_GLOBAL_BIN_DIR` error while installing Preflight. This error occurs when a `pnpm` command is run before the global bin directory has been created using the `pnpm setup` command. To prevent this error, we are adding the `pnpm setup` command to the system setup guide that sets up this directory mentioned in this [Node.js/corepack issue](https://github.com/nodejs/corepack/issues/216).  
- Explicit testing on Linux/Ubuntu has not been performed in this PR
- The suggested `sudo pnpm setup` command for Linux mentioned in this [comment](https://github.com/upleveled/system-setup/issues/58#issuecomment-2023712876) is not used in the install script
> Avoid ERR_PNPM_NO_GLOBAL_BIN_DIR error 

- linux.md
Some Students don't have Vim as the default manager on Linux. This PR changes the system setup guide to use Vim as the default Git editor. To follow the logical steps, I added this new guide to the default Git branch `master` to `main` step. The logical order for me is: 
24) Git credentials for user
25) Git credentials storage
26) Default behavior changes in Git. Branch from `master` to `main` and default editor to Vim.
> Set Vim as default editor for Git on Linux

- linux.md
- macos.md
- windows.md
From the VS Code ESLint extension [v3.0.5 prerelease notes](https://github.com/microsoft/vscode-eslint#version-305---pre-release):
> ## Version 3.0.5 - pre-release
>
> Support for the new ESLint flat config files has improved. The following changes have been implemented:
>
> To use flat config files it is recommended to use ESLint version 8.57.0 or above.
There is a new `eslint.useFlatConfig` setting which is honored by ESLint version 8.57.0 and above. If one of those versions is used, the extension adheres to the [ESLint Flat config rollout plan](https://eslint.org/blog/2023/10/flat-config-rollout-plans/). The setting has the same meaning as the environment variable `ESLINT_USE_FLAT_CONFIG`.
>
> The experimental settings `eslint.experimental.useFlatConfig` is deprecated and should only …
> Remove unnecessary useFlatConfig setting

- linux.md
- macos.md
- windows.md
Switch from [`create-expo`](https://www.npmjs.com/package/create-expo) to [`create-expo-app`](https://www.npmjs.com/package/create-expo-app), because the Expo docs use this:
- https://docs.expo.dev/get-started/create-a-project/
- https://docs.expo.dev/more/create-expo/
Also switch from the [`blank`](https://github.com/expo/expo/tree/main/templates/expo-template-blank) template to [`blank-typescript`](https://github.com/expo/expo/tree/main/templates/expo-template-blank-typescript), because we teach Expo with TypeScript
> Switch to create-expo-app + blank-typescript, remove .npmrc cmds

- windows.md
Closes #41 
Our System Setup Guide for Windows failed when the Windows Execution Policy is set to `Restricted`, which prevents script execution. This PR updates the Windows System Setup Guide and sets the [execution policy](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-5.1#-executionpolicy) to `AllSigned`, this requires that all scripts and configuration files are signed by a trusted publisher, including scripts written on the local computer.
> Change execution policy for Windows to allow running scripts 

- windows.md
Closes #41 
Follow-up to #84 and #85 
Our System Setup Guide for Windows failed when the Windows Execution Policy is set to `Restricted`, which prevents script execution. This PR updates the Windows System Setup Guide and sets the [execution policy](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-5.1#-executionpolicy) to `AllSigned`, this requires that all scripts and configuration files are signed by a trusted publisher, including scripts written on the local computer.
> Change execution policy for Windows to allow running scripts

- linux.md
- macos.md
- windows.md
Time zone inconsistencies between systems (eg. development environment and production environment) can be very difficult to debug.
Instead, set PostgreSQL to use UTC time (which seems to be best practice for deployment infrastructure, from a quick search)
TODO:
Useful commands:
```bash
SHOW TIMEZONE;
cat $PGDATA/postgresql.conf | grep timezone
tzutil /g # Windows (unverified)
sudo systemsetup -gettimezone # macOS
timedatectl # Linux (unverified)
```
Note: The checks above should be done anyway, because we support latest PostgreSQL (currently PostgreSQL v16)
But just for documentation / posterity:
On my local system (macOS PostgreSQL v14, via Homebrew), here's the output of `SHOW TIMEZONE;` before this config:
```
=> SHOW TIMEZONE;
TimeZone
---------------
Europe/Vienna
(1 row)
```
In my …
> Configure PostgreSQL time zone to UTC

- linux.md
- macos.md
- windows.md
Running the Perl scripts in the current order causes an error as Perl cannot find the file path needed to the `postgresql.conf`
The shell needs to be sourced after Postgres installation and `PGDATA` setup before Perl can be run successfully. Changing the order of Perl commands in the setup guide so that students will run it when the file it need is ready
> Reorder Perl scripts to run after shell sourcing

- linux.md
- macos.md
- windows.md
Closes https://github.com/upleveled/system-setup/issues/47
The solution provided in https://github.com/upleveled/system-setup/pull/80 caused a new error `postmaster became multithreaded during startup` as postgres server could not be started in macOS terminal if the `LANG` locale is not set. This was not noticed during the PR because the iTerm2 used for the testing sets the `LANG` locale automatically but the macOS terminal does not.
The `FATAL:  postmaster became multithreaded during startup` error could be caused by anything, but these are the things we know now so far
1. When the `LANG` environment variable is unset to `LANG=` or `LANG=""`, the above error will occur. When running Postgres from iTerm2, this error doesn't occur because [iTerm2 sets this `LANG` environment variable by …
> Replace Perl Locale update with LANG env setting

- windows.md
Related to #91 
Discussed in this [comment](https://github.com/upleveled/system-setup/pull/91#issuecomment-2264962880) 
This PR updates the Windows setup commands to use `~` instead of `$USERPROFILE` or `$HOME` when referring to the home directory.
> Standardise Home Directory in Windows Setup commands

- windows.md
- https://github.com/pnpm/pnpm/issues/8444
On Windows when running `pnpm setup`, Powershell throws an error:
```
>> pnpm setup
Preparing pnpm@latest for immediate activation...
pnpm : File C:\Program Files\nodejs\pnpm.ps1 cannot be loaded. The file C:\Program Files\nodejs\pnpm.ps1 is not
digitally signed. You cannot run this script on the current system. For more information about running scripts and
setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:3 char:1
+ pnpm setup
+ ~~~~
+ CategoryInfo          : SecurityError: (:) [], PSSecurityException
+ FullyQualifiedErrorId : UnauthorizedAccess
```
This PR adds a workaround to the installation script to handle PowerShell's execution policy on Windows systems. I temporarily sets the …
> Add Windows PowerShell execution policy workaround for pnpm setup

- macos.md
Originally, in some cases [PostgreSQL logs didn’t appear in the terminal for Windows users](https://github.com/upleveled/system-setup/issues/81), we didn't investigate and fix this at the time. Instead, we included a new section in both the Windows and macOS guides to [demonstrate different outputs](https://github.com/upleveled/system-setup/commit/a69f0da381b3153b3cca3d33fd4d293d7ad17264) when starting PostgreSQL. 
We later decided to investigate and show the logs permanently for all students by [disabling the logging_collector on Windows](https://github.com/upleveled/system-setup/pull/87), which as a side-effect, made the screenshots mostly the same for macOS. 
Since we decided to show the logs in the terminal, this PR removes the Windows-specific PostgreSQL start command section from …
> Remove Windows specific PostgreSQL section from macOS guide

- windows.md
Ref https://github.com/upleveled/system-setup/issues/97
This PR adds a [`-Force` parameter to the Windows Set-ExecutionPolicy command](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.4#-force) to remove confirmation prompts before running `pnpm setup`.
> Set Execution Policy with -Force to avoid confirmation prompts

- linux.md
- macos.md
- windows.md
To reduce risk of student environments being affected by npm supply chain attacks such as the recent high profile [Qix package attacks](https://socket.dev/blog/npm-author-qix-compromised-in-major-supply-chain-attack) and [Nx package attacks](https://socket.dev/blog/nx-packages-compromised), configure pnpm to install package versions that are at least 7 days old.
This is also tested and documented on pnpm Tricks and the related reproduction repo:
- https://github.com/karlhorky/pnpm-tricks#configure-minimumreleaseage-and-minimumreleaseageexclude-globally
- https://github.com/karlhorky/repro-pnpm-minimumReleaseAgeExclude-global-cross-platform
> Configure 7 day `minimumReleaseAge` for pnpm
